[package]
name = "omni"
version = "0.1.0"
edition = "2021"


[workspace]
members = [
	"crates/omni-parser"
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


