[package]
name = "omni"
version = "0.0.0"
description = "An IDL and Codegen tool to reduce client/server boilerplate"
keywords = [
	"idl",
	"smithy",
	"codegen",
	"cli"
]

[workspace]
members = [
	"crates/parser",
]


[workspace.dependencies]
nextest = "0.0.0"




