[package]
name = "omni"
version = "0.0.0"
edition = "2021"
description = "An IDL and Codegen tool to reduce client/server boilerplate"
keywords = [
	"idl",
	"smithy",
	"codegen",
	"cli"
]

[workspace]
members = [
	"omni_parser",
]


[dependencies]
omni_parser = { path = "./omni_parser", version = "0.0.0" }

[dev-dependencies]
assert_cmd = "2.0.12"
dir-diff = "0.3.2"
nextest = "0.0.0"




